export const _playerData = [
  {
    name: "Fiston Mayele",
    position: "CF",
    kitNo: 9,
    team: "Young Africans",
    marketValue: "4OOM",
    age: 23,
    nationality: "Tanzanian",
  },
  {
    name: "Fiston Mayele",
    position: "CF",
    kitNo: 9,
    team: "Young Africans",
    marketValue: "4OOM",
    age: 23,
    nationality: "Tanzanian",
  },
  {
    name: "Fiston Mayele",
    position: "CF",
    kitNo: 9,
    team: "Young Africans",
    marketValue: "4OOM",
    age: 23,
    nationality: "Tanzanian",
  },
  {
    name: "Fiston Mayele",
    position: "CF",
    kitNo: 9,
    team: "Young Africans",
    marketValue: "4OOM",
    age: 23,
    nationality: "Tanzanian",
  },
  {
    name: "Fiston Mayele",
    position: "CF",
    kitNo: 9,
    team: "Young Africans",
    marketValue: "4OOM",
    age: 23,
    nationality: "Tanzanian",
  },
  {
    name: "Fiston Mayele",
    position: "CF",
    kitNo: 9,
    team: "Young Africans",
    marketValue: "4OOM",
    age: 23,
    nationality: "Tanzanian",
  },
];
